apiVersion: v1
kind: Service
metadata:
  name: movezy-backend
  labels:
    app: movezy-backend
spec:
  selector:
    app: movezy-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
